version: "3"

services:
  db:
    image: "postgres:13.7-alpine"
    container_name: "cbrf_exchange_rates_db"
    env_file:
      - variables.env
    restart: always
    ports:
      - "${DOCKER_DB_PORT}:5432"
    volumes:
      - ${DOCKER_DB_DATA}:/var/lib/postgresql/13/data
  grafana:
    image: "grafana/grafana-oss"
    container_name: "grafana"
    restart: always
    ports:
      - "3000:3000"
